export const data = [
    `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
    `It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).`,
    `Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.`,
    `There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.`,
    `The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.`,
    `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec nulla nisl, interdum ac rutrum ac, elementum ut mi. Duis vehicula turpis a vehicula convallis. Nullam gravida erat magna, non luctus ex lobortis vitae. Praesent tellus odio, dapibus quis metus ut, sodales congue dui. Quisque accumsan massa quis dui sodales congue. Mauris placerat vitae ipsum et scelerisque. Aenean pellentesque interdum magna. Phasellus nec arcu ut enim tempus pretium. Proin augue eros, blandit tempor felis porttitor, pharetra ultrices eros. Proin aliquet nibh ac enim tincidunt, in imperdiet magna facilisis. Nunc in ligula laoreet, imperdiet tellus ut, rhoncus elit.`,
    `Mauris magna ante, hendrerit vitae posuere in, scelerisque id felis. Sed eu metus id mi pharetra venenatis. Fusce faucibus bibendum sodales. Maecenas a turpis id mauris ornare auctor non a odio. Proin luctus pulvinar lorem sed elementum. Curabitur a enim volutpat, placerat massa ut, consequat lectus. Donec hendrerit sapien vitae nunc euismod, vel commodo purus eleifend. Praesent rutrum blandit efficitur. Curabitur quam sapien, cursus eu ornare in, euismod sed dui. Proin nec lacus a ante rutrum congue. Phasellus vehicula lectus a arcu dignissim luctus. Cras vitae suscipit quam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ullamcorper quam ipsum. Morbi ultrices tortor velit, vitae lobortis tellus vehicula vel. Donec auctor, magna commodo lacinia dictum, felis quam iaculis lorem, nec aliquet odio augue vitae felis.`,
    `Praesent sed cursus dui, ac convallis sem. Quisque venenatis sem nec quam aliquet lacinia. Donec efficitur elementum fringilla. Vivamus scelerisque non libero fermentum venenatis. In fermentum mi ac diam molestie, a lacinia libero feugiat. Donec sagittis lorem eu dictum lobortis. Donec et mattis lacus. Suspendisse varius elit et consequat tincidunt. Duis ut sapien nulla. Curabitur ornare tortor id tempor ornare. In hac habitasse platea dictumst.`,
    `Sed sit amet rutrum nunc, non vulputate mauris. Praesent ac bibendum ligula. Nunc at orci turpis. In lobortis ante a diam varius porta. Aenean ullamcorper tempor nulla ut dignissim. Phasellus vel condimentum dui. Nunc auctor tellus sed urna convallis consequat.`,
    `Integer et tempor massa. Fusce risus libero, pharetra sit amet massa cursus, consectetur mollis leo. Donec placerat sollicitudin leo, non auctor nibh volutpat eu. Mauris imperdiet eros tortor, ornare ornare magna sollicitudin eu. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam ut pharetra nulla. Sed at nisi sit amet ipsum lacinia luctus. Pellentesque quis metus nec magna tincidunt vulputate et id mi. Aliquam elementum massa eget tortor eleifend sodales eget vel dolor. Vestibulum porttitor sit amet justo nec molestie. Morbi tempus, ligula a faucibus ornare, dui libero imperdiet ipsum, vitae suscipit ante purus et ante.`,
]